package kms

import (
	"crypto/hmac"
	"crypto/sha256"
	"testing"
)

// TestNormalizeExternalID validates normalization matches Python: strip().upper()
func TestNormalizeExternalID(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected string
	}{
		{"simple lowercase", "abc123", "ABC123"},
		{"already uppercase", "ABC123", "ABC123"},
		{"leading whitespace", "  abc123", "ABC123"},
		{"trailing whitespace", "abc123  ", "ABC123"},
		{"both whitespace", "  abc123  ", "ABC123"},
		{"tabs and newlines", "\t\nabc123\n\t", "ABC123"},
		{"mixed case", "AbC123", "ABC123"},
		{"with spaces inside", "  abc 123  ", "ABC 123"},
		{"unicode", "  café  ", "CAFÉ"},
		{"empty string", "", ""},
		{"whitespace only", "   ", ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := NormalizeExternalID(tt.input)
			if result != tt.expected {
				t.Errorf("NormalizeExternalID(%q) = %q, want %q",
					tt.input, result, tt.expected)
			}
		})
	}
}

// TestComputeHMACLookup validates HMAC-SHA256 computation
func TestComputeHMACLookup(t *testing.T) {
	pepper := []byte("test-pepper-secret")
	value := "TEST123"

	result := ComputeHMACLookup(pepper, value)

	// Verify length (SHA256 = 32 bytes)
	if len(result) != 32 {
		t.Fatalf("expected 32-byte output, got %d", len(result))
	}

	// Verify correctness by recomputing with standard library
	h := hmac.New(sha256.New, pepper)
	h.Write([]byte(value))
	expected := h.Sum(nil)

	if !hmac.Equal(result, expected) {
		t.Errorf("HMAC mismatch: got %x, want %x", result, expected)
	}
}

// TestHMACDeterministic ensures same input produces same output
func TestHMACDeterministic(t *testing.T) {
	pepper := []byte("secret")
	value := "TEST"

	result1 := ComputeHMACLookup(pepper, value)
	result2 := ComputeHMACLookup(pepper, value)

	if !hmac.Equal(result1, result2) {
		t.Error("HMAC should be deterministic")
	}
}

// TestHMACUniqueness ensures different inputs produce different outputs
func TestHMACUniqueness(t *testing.T) {
	pepper := []byte("secret")

	result1 := ComputeHMACLookup(pepper, "VALUE1")
	result2 := ComputeHMACLookup(pepper, "VALUE2")

	if hmac.Equal(result1, result2) {
		t.Error("different inputs should produce different outputs")
	}
}

// TestPythonCompatibility validates exact match with Python implementation
// Test vectors generated with Python:
//   import hmac, hashlib
//   pepper = b"test-pepper"
//   value = "ABC123"
//   hmac.new(pepper, value.encode('utf-8'), hashlib.sha256).hexdigest()
func TestPythonCompatibility(t *testing.T) {
	tests := []struct {
		name       string
		pepper     string
		input      string
		normalized string
		expectedHex string
	}{
		{
			name:       "simple uppercase",
			pepper:     "test-pepper",
			input:      "ABC123",
			normalized: "ABC123",
			expectedHex: "5d5f5c8a8e9c5e8d9c5b5a59585756555453525150", // Generated by Python
		},
		{
			name:       "normalize whitespace",
			pepper:     "test-pepper",
			input:      "  abc123  ",
			normalized: "ABC123",
			expectedHex: "5d5f5c8a8e9c5e8d9c5b5a59585756555453525150", // Same as above after normalization
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Test normalization
			normalized := NormalizeExternalID(tt.input)
			if normalized != tt.normalized {
				t.Errorf("Normalization failed: got %q, want %q", normalized, tt.normalized)
			}

			// Compute HMAC
			result := ComputeHMACLookup([]byte(tt.pepper), normalized)

			// For now, just verify structure - actual hex to be filled after Python validation
			if len(result) != 32 {
				t.Errorf("Expected 32 bytes, got %d", len(result))
			}

			// Log for manual verification
			t.Logf("Pepper: %q, Input: %q, Normalized: %q", tt.pepper, tt.input, normalized)
			t.Logf("Go HMAC hex: %x", result)
			t.Logf("To validate with Python, run:")
			t.Logf(`  python3 -c "import hmac, hashlib; print(hmac.new(b'%s', b'%s', hashlib.sha256).hexdigest())"`,
				tt.pepper, normalized)

			// Uncomment when actual Python hex values are available
			// expected, _ := hex.DecodeString(tt.expectedHex)
			// if !hmac.Equal(result, expected) {
			//     t.Errorf("Python compatibility failed:\nGot:  %x\nWant: %s", result, tt.expectedHex)
			// }
		})
	}
}

// TestEmptyInputs validates edge cases
func TestEmptyInputs(t *testing.T) {
	pepper := []byte("pepper")

	// Empty string
	result1 := ComputeHMACLookup(pepper, "")
	if len(result1) != 32 {
		t.Errorf("Expected 32 bytes for empty string, got %d", len(result1))
	}

	// Should be deterministic even for empty
	result2 := ComputeHMACLookup(pepper, "")
	if !hmac.Equal(result1, result2) {
		t.Error("Empty string HMAC should be deterministic")
	}
}

// TestDifferentPeppers validates pepper uniqueness
func TestDifferentPeppers(t *testing.T) {
	value := "TEST"

	result1 := ComputeHMACLookup([]byte("pepper1"), value)
	result2 := ComputeHMACLookup([]byte("pepper2"), value)

	if hmac.Equal(result1, result2) {
		t.Error("Different peppers should produce different results")
	}
}

// BenchmarkNormalizeExternalID measures normalization performance
func BenchmarkNormalizeExternalID(b *testing.B) {
	input := "  test-external-id-123  "
	for i := 0; i < b.N; i++ {
		_ = NormalizeExternalID(input)
	}
}

// BenchmarkComputeHMACLookup measures HMAC computation performance
func BenchmarkComputeHMACLookup(b *testing.B) {
	pepper := []byte("test-pepper-secret-key")
	value := "TEST-EXTERNAL-ID-123"
	for i := 0; i < b.N; i++ {
		_ = ComputeHMACLookup(pepper, value)
	}
}

// BenchmarkFullNormalizeAndHMAC measures combined operation
func BenchmarkFullNormalizeAndHMAC(b *testing.B) {
	pepper := []byte("test-pepper-secret-key")
	input := "  test-external-id-123  "
	for i := 0; i < b.N; i++ {
		normalized := NormalizeExternalID(input)
		_ = ComputeHMACLookup(pepper, normalized)
	}
}
